apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-db-combined
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-db-combined
  template:
    metadata:
      labels:
        app: app-db-combined
    spec:
      containers:
      - name: db-kub
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "orbidi"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      - name: app
        image: ccastri/fastapi-back:0.0.1
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "orbidi"
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-pvc
