apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
data:
  DB_HOST: ZGIN
  DB_PORT: NTQzMg0=
  DB_USER: cG9zdGdyZXMN
  DB_PASSWORD: cGFzc3dvcmQN #Check password matching cause enconding has some differences
  DB_NAME: b3JiaWRpCg==
  PGADMIN_DEFAULT_EMAIL: ZW1haWxAZXhhbXBsZS5jb20K   # Aquí irá el valor codificado en base64 de PGADMIN_DEFAULT_EMAIL
  PGADMIN_DEFAULT_PASSWORD: cGFzc3dvcmQK