apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ccastri/cyc-front:1.1  # Usa la imagen que subiste a Docker Hub
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        - name: CHOKIDAR_USEPOLLING
          value: "true"
        - name: WATCHPACK_POLLING
          value: "true"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 40
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 40
          periodSeconds: 30
